version: "3.8"
services:
  backend:
    build:
      dockerfile: dockerfile.prod
    image: backend:latest
    container_name: medusa-server
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://ezitech_user:yBAKOzXTzOSUJP1N0bPqPTpW8QhhWOhV@dpg-csda8mpu0jms73b9gm1g-a.oregon-postgres.render.com/ezitech?sslmode=require
      NODE_ENV: production
      STORE_CORS: http://localhost
    ports:
      - "9000:9000"

  postgres:
    restart: always
    environment:
      POSTGRES_USER: ezitech
      POSTGRES_PASSWORD: ecoville
      POSTGRES_DB: ezitech

  redis:
    restart: always
